### ISSUE TITLE
Packagist?

### ISSUE THREAD

**Issue by gstjohn** [tailwind/fastimage#5]
Hey -- Great updates to this package. It looks like the original is pretty well abandoned. Do you plan to set up a Packagist package for this so it's easier to grab with Composer? Are you actively maintaining this package? Thanks!

**Comment by willwashburn** [comment]
Hey @gstjohn thanks!

We're actively using this branch but had not planned on putting it into packagist. We've been using it with composer as a a VCS repository. It looks like there are a few other forks of this fork that have already added it to packagist.

We do want to contribute back and are happy to take PR's on this fork though!

**Comment by gstjohn** [comment]
Not a problem at all. I do need it on Packagist for my public project (https://github.com/gstjohn/Thumbsnag) and so I am one of those forks. Will be happy to push back any changes I make through PR. Thanks for your work on this.
